### PR TITLE
Build wheels for Python 2.7 again

### PR DESCRIPTION
**Pull request by cdce8p**

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
@cdce8p — Yes, thank you for this pull request! It has been an open tab over on the left side of my browser for a few weeks, during which I've had other projects demanding my attention — but I'm planning to merge as soon as my attention can be turned back to PyEphem, probably by the end of the year!

**Comment by cdce8p** [comment]
Requires #278 to be merged first.

**Comment by brandon-rhodes** [comment]
I just did the merge, so you should be able to go ahead and rebase! Thanks for making this pull request active again; it fell off my radar during a busy winter and, obviously, I hadn't yet returned to it.

**Comment by cdce8p** [comment]
> I just did the merge, so you should be able to go ahead and rebase! Thanks for making this pull request active again; it fell off my radar during a busy winter and, obviously, I hadn't yet returned to it.

It's all working now. I needed to fall back to `macos-13` as `macos-latest` uses the M1 chip and is not compatible with Python 2.7.

Also added a small changelog entry for the Python 3.13 support. With that you should be able to just merge it into `release` afterwards.

**Comment by cdce8p** [comment]
Checks are all green. This is ready now 🚀

**Comment by brandon-rhodes** [comment]
One quick question before we merge: do the checks that ran on this PR test whether the `github-deploy.yml` actions will run successfully? Or, will they receive their first-and-only test after merging, when I advance the `release` branch to include this commit?

(And, if they haven't run yet in this PR: should we adjust things so that those actions run here, though without the credentials they would need to do a real upload to PyPI?)

**Comment by cdce8p** [comment]
> One quick question before we merge: do the checks that ran on this PR test whether the `github-deploy.yml` actions will run successfully? Or, will they receive their first-and-only test after merging, when I advance the `release` branch to include this commit?

I've been testing the workflow on my fork (with a modified trigger to run on push). So I'm quite confident that it will work. The only slight unknown is the `pypa/gh-action-pypi-publish@release/v1` action as I couldn't test that. However, the upload with API key should continue to work even if [Trusted publishing](https://github.com/pypa/gh-action-pypi-publish/tree/release/v1/?tab=readme-ov-file#trusted-publishing) is the recommended option nowadays.

> (And, if they haven't run yet in this PR: should we adjust things so that those actions run here, though without the credentials they would need to do a real upload to PyPI?)

That would be an option although I'm not sure it's fully necessary. Especially the `build_wheels` job takes quite a while. So we would need some kind of limited setup and mostly end up where we're now anyways. The breaking change for the artifact actions was the most tricky to work out, but hopefully that won't be repeated anytime soon.

**Comment by brandon-rhodes** [comment]
> I've been testing the workflow on my fork…

Good! Thank you for the reassurance. As soon as the new slate of tests passes, I'll plan to merge and the advance the `release` branch and see if new versions appear on PyPI or not.

**Comment by cdce8p** [comment]
> > I've been testing the workflow on my fork…
> 
> Good! Thank you for the reassurance. As soon as the new slate of tests passes, I'll plan to merge and the advance the `release` branch and see if new versions appear on PyPI or not.

Awesome, thanks! Sorry about the multiple commits btw. I pushed the last one only after reading #256.

**Comment by brandon-rhodes** [comment]
IT WORKED! I see Python 2.7 and 3.13 builds now listed on PyPI!

Thanks so much for putting this together. 🙂

**Comment by cdce8p** [comment]
> IT WORKED! I see Python 2.7 and 3.13 builds now listed on PyPI!
> 
> Thanks so much for putting this together. 🙂

Awesome 🚀

Would you mind creating the `4.1.6` tag on Github?
https://github.com/brandon-rhodes/pyephem/tags

**Comment by brandon-rhodes** [comment]
> Would you mind creating the 4.1.6 tag on Github?

Done.

**Pull request merged**
