### PR TITLE
Add CMake configuration to build a shared library for general use

### PR DESCRIPTION
**Pull request by klaussnd**
This PR adds a CMake configuration whose aim is to build a shared libastro C library. This library can be used for example in C or C++ applications. It was tested to work on Linux, Windows, and MacOS X. All functions are exported. The Python build process is not altered.

### CODE REVIEW

**Comment by klaussnd** [comment]
I don't understand why the CI breaks on Windows.

Tarvis: "An error occurred while generating the build script." What does that mean? 

AppVeyor: self.assertAlmostEqual(t.earth_distance, 0.0296238418669, 10)
AssertionError: 0.00017109312466345727 != 0.0296238418669 within 10 places
Why should the earth radius change just because I add a CMake configuration?

**Comment by brandon-rhodes** [comment]
Now that I finally have time to return to this old project: I'm interested in either discussing this pull request and seeing if we can work out the CI issue you say, or else talking about whether you should create a dedicated repository for libastro that would include just its source code and the cmake file — if the goal is to have it reused, it might be helpful for integrators to be able to pull the library separately from this particular PyEphem project?

In any case, the errors I see in CI at the moment don't seem to involve precision, but an inability of the library to compile because it can't find the library in `#include "astro_export.h"` — are you seeing the same error, or are the CI links leading you to different test results?

And: try focusing on the Travis results first. The appveyor results sometimes have other failures.

**Comment by drbitboy** [comment]
That AppVeyor accuracy issue only occurs on the 64-bit builds.

Also, for the test in question, it is the distance between an object ("P10frjh") in a heliocentric elliptical orbit, which orbit is defined by the pyephem.readdb() string argument in the XEphem database format, and the Earth, which orbit is defined internally in XEphem.  There are two positions being calculated internally by libastro:  that of P10frjh; that of Earth.  It would be worth adding checks of their positions to that test to see where the difference occurs.

There are many "assigning double to float" warnings in the 64-bit build, but they also show up in the 32-bit builds.  So while that is unlikely to be the problem, it is not impossible as the tested value is a small difference between large values (I would guess this is near the closest approach to Earth by some comet ...

Wait a minute, as search of P10frjh yielded this as the first hit:

  https://github.com/brandon-rhodes/pyephem/issues/58

  "Getting incorrect data for near earth objects in windows(64bit) #58"

hmm, I'm not done reading, but it does seem we've been here before ...

**Comment by drbitboy** [comment]
for grins and giggles, try some form this printf:

  printf("float_rho = %f\n", *((float*)(&rho)));

Also, your %f's should be %lf when printing doubles, although the compiler usually figures that out.

Brian

**Comment by klaussnd** [comment]
Suggestion: If this is an upstream issue that is unconnected to this PR, maybe it should be fixed outside this PR.

**Comment by marco-m** [comment]
Hello, any news ? Could a maintainer please summarise what is still needed for this PR to be accepted ?

**Comment by brandon-rhodes** [comment]
The last time I'd checked discussion about floating point was still going on, and I'd not seen a conclusion — and, what I clearly need is a mechanism that brings an open pull request back to the top of my GitHub queue when it's been, say, 10 days since the last comment. It alerts me when there is new discussion, but not when discussion finally halts.

I'd ask for `astro_export.h` to be moved, but I feel that the pull request has languished open for too long for me to ask for any round trips, so I'll go ahead and merge!

**Comment by barrycarter** [comment]
I was thinking a solution using ifttt.com or a similar website. They don't currently have staleness triggers, but it should be possible to add some, and they could help people in many other ways as well.

**Pull request merged**
