### PR TITLE
using Python 3 print() function in README example

### PR DESCRIPTION
**Pull request by miki725**
Since the lib supports Python 3, maybe use that as example in README.

Please note that needed to add the `__future__` import so that in Py2, it will not print a tuple.

### CODE REVIEW

**Comment by miki725** [comment]
@brandon-rhodes when you have a chance, can you take a look at the changes. Thanks for the previous recommendation. I makes complete sense that `__future__` will be confusing to beginners.

**Comment by brandon-rhodes** [comment]
Thanks! I combined your commits into a single commit and merged it under your name as 88e35eb — thanks for contributing, this is much better for new users!

**Comment by miki725** [comment]
awesome. glad was able to help!

**Comment by brandon-rhodes** [comment]
The new front page will probably go live this weekend, when I have time to write up the new links to the release I just made this week, so watch for the web site to contain the new code. Thanks again!

**Pull request closed without merging**
