### PR TITLE
GitHub issue #63

### PR DESCRIPTION
**Pull request by dmopalmer**
Modified next_pass() to give rise,culminate,set for a single pass.
Pass singlepass=False to get old behavior,

### CODE REVIEW

**Comment by dmopalmer** [comment]
This pull request has been modified twice, most recently the morning (US MDT) of Sept 30.

**Comment by dmopalmer** [comment]
Brandon,

Is there a reason why this hasn't been pulled?  (Apart from the obvious prioritization.)

**Comment by brandon-rhodes** [comment]
I have been a bit stalled on PyEphem trunk — after adding a few debugging statements to `master` to try to understand why it fails on 64-bit Windows (see the appveyor results attached to this pull request), I can see that a wrong value is being generated but cannot determine why. I wonder if I will need to just abandon Windows as a supported platform for the time being?

When I am at PyCon Canada this coming weekend and at the sprints, I will see whether I can bring any expertise to bear on the problem so that, one way or another, PyEphem can start working again on the platforms it supports and move forward in other areas, and will update this pull request with a plan for how to move forward!

**Comment by eamanu** [comment]
Hi Brandon, 

I see the Win(64bit) pyephem problem. That is a interesting problem. I will try to study it. 

Anyway, I recommend you create two branch, one with Windows support and other with Linux support, until we can solve the problem. This way, you could merge PR dinamically.

**Pull request merged**
